
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Cdc_member/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>

<h1 id="homeHeading">SELAMAT DATANG UWP</h1>
<h2 id="homeHeading">Aplikasi Survey Mahasiswa</h2>

<body id="page-top" style="margin-top: 50px; background-color:pink;" 

   

<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-lg-offset-2 col-md-offset-2">
			

<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
             

                  <form name="form_bpm_angket_mahasiswa" id="form_bpm_angket_mahasiswa" action="<?= base_url('index.php/administrator/bpm_angket_mahasiswa/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            No Angket
                           </th>
                           <th>Angket</th>
                           <th>Nim</th>
                           <th>Periode</th>
                           <th>Active</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_bpm_angket_mahasiswa">
                     <?php foreach($bpm_angket_mahasiswas as $bpm_angket_mahasiswa): ?>
                        <tr>
                           <td width="5">
                              <?= $bpm_angket_mahasiswa->id; 
							  
							
							  ?>
                           </td>
                           <?php
						   
						   if (!empty($bpm_angket_mahasiswa->iddosen))
							{
						    $querynamadsn = $this->db->query("select nama from kepegawaian_ms_pegawai where nip = '".$bpm_angket_mahasiswa->iddosen."'");
							foreach ($querynamadsn->result() as $dsn)
							{ 
								$namadosen=$dsn->nama;
								$this->data['namadosen'] = $namadosen;
							}
							$querynamamk = $this->db->query("select kur.namamk from ".$bpm_angket_mahasiswa->periode."_akademik_ak_mengajar as ajr, ".$bpm_angket_mahasiswa->periode."_akademik_ak_kurikulum as kur  where ajr.kodemk = kur.kodemk and ajr.nipdosen = '".$bpm_angket_mahasiswa->iddosen."' and ajr.kodemk = '".$bpm_angket_mahasiswa->kodemk."' and ajr.periode = ".$bpm_angket_mahasiswa->periode." and ajr.kelasmk = '".$bpm_angket_mahasiswa->kelasmk."';

							");
							foreach ($querynamamk->result() as $mk)
							{ 
								$namamk=$mk->namamk; 
								$this->data['namamk'] = $namamk;
							}
							}
							else
							{
								$namadosen = 'biro'; 
								$this->data['namadosen'] = $namadosen;
								$namamk ='';
								$this->data['namamk'] = $namamk;
							}  
							
							
						   ?> 
                           <td><?php echo($bpm_angket_mahasiswa->angket."(".$namadosen."-".$namamk.")"); ?></td>
                             
                           <td><?php echo($bpm_angket_mahasiswa->nim); ?></td> 
                           <td><?php echo($bpm_angket_mahasiswa->periode); ?></td> 
                           <td><?php echo($bpm_angket_mahasiswa->active); ?></td> 
                           <td width="200">
						   
						  
							   sd
								
								<?php
								$js = $this->db->query("select bs.id, count(*) as jum_soal from bpm_angket as ba, bpm_soal as bs,bpm_angket_detail as bad where 
														bad.id_angket = ba.id 
														and bad.id_soal = bs.id 
														and ba.id = ".$bpm_angket_mahasiswa->id_angket.";");   
								foreach ($js->result() as $r)
								{
								$jum_soal=$r->jum_soal;	
								echo "Instrumen ".$jum_soal." ";
								}
								
								
								$cari = $this->db->query("select count(*) as jumlah from ".$bpm_angket_mahasiswa->periode."_bpm_survey_value as bsv where bsv.id_angket_mahasiswa = ".$bpm_angket_mahasiswa->id." and (bsv.skor <> null or bsv.skor <> 0)");
								foreach ($cari->result() as $row)
								{
								$terisi=$row->jumlah;	
								}
								
								echo "Terisi ".$terisi." ";
								
								$belum_terisi = $jum_soal - $terisi;
								
								?>
								<br>  
								
								
							    <?php  
								
								 
									
										if($belum_terisi<>0){
							
								?>
								 
								<a href="<?= base_url('index.php/survey_value/isi_angket?nim='.$bpm_angket_mahasiswa->nim.'&periode='.$bpm_angket_mahasiswa->periode.'&angket=' . $bpm_angket_mahasiswa->id_angket."&id_angket_mahasiswa=".$bpm_angket_mahasiswa->id."&namadsn=".$this->data['namadosen']."&namamk=".$this->data['namamk']); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> isi angket
								<?php ;}
 
									 else
									 {
										 echo "data telah terisi"; 
									 }
									
								
								
								
								

								?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($bpm_angket_mahasiswa_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Bpm Angket Mahasiswa data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
              
			   
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>

<font color="white">@dev by: BasuKarna</font>

	</div>
	</div>

