
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Cdc_member/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<body id="page-top" style="margin-top: 50px;" style="background-color:pink;">



<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-lg-offset-2 col-md-offset-2">
			
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
              

                  <!--<form name="form_bpm_soal" id="form_bpm_soal" action="<?= base_url('administrator/bpm_soal/index'); ?>">
                 -->
					<?= form_open(base_url('Survey_value/simpan_value_angket'), [
                            'name'    => 'form_bpm_survey_value', 
                            'class'   => 'form-horizontal', 
                            'id'      => 'form_bpm_survey_value', 
                            'enctype' => 'multipart/form-data', 
                            'method'  => 'POST'
                            ]); ?> 
			
				<input type="hidden" name="npm" placeholder = "isikan npm di sini" value="<?php echo $nim; ?>">
				<input type="hidden" name="periode" placeholder = "isikan periode di sini" value="<?php echo $periode; ?>"> 
				<input type="hidden" name="nama" placeholder = "isikan nama di sini" value=" ">
				<?php
				
				//echo $namadosen;
				//echo $namamk;
				 
				?>
				<input type="hidden" name="id_angket" placeholder = "isikan id_angket" value="<?php echo $angket; ?>">  
				<input type="hidden" name="id_angket_mahasiswa" placeholder = "isikan id_angket_mahasiswa" value="<?php echo $id_angket_mahasiswa; ?>">  
				   
				<br>
				<input type="hidden" name="id_angket_mahasiswa" placeholder = "isikan id_angket" value="<?php echo $id_angket_mahasiswa; ?>">
				<br>   
				<?php //echo $query; ?>
				<b>Petunjuk : </b>
				<br> 
				
				<ul>
				<li>1. Isilah angket ini sesuai kondisi yang saudara alami. Masukan saudara 
				sangat berguna untuk meningkatkan kualitas pelayanan kemahasiswaan</li>
				<li>2. Pilih opsi radio button pada jawaban yang saudara pilih</li>
				<li>3. Setiap pertanyaan diberikan 4 pilihan jawaban dengan keterangan :
				1 = sangat tidak setuju; 2 = tidak setuju; 3 = setuju; 4 = sangat setuju</li>
				<!--<li></li>-->
				
				</ul>
				 

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <!--<th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>-->

						   <th rowspan="2">No.</th>
                           <th rowspan="2">Aspek Yang Dinilai</th>
						   <th colspan="4"><center>Skor</center></th>   
                           <!--<th>Action</th>-->
                        </tr> 
						<tr class="">
                         
						   <td>1</td>   
                           <td>2</td>
						   <td>3</td>
						   <td>4</td>
						  
                        </tr> 
				
                     </thead>
                     <tbody id="tbody_bpm_soal">
					 <?php $no = 0;?>
                     <?php foreach($bpm_soals as $bpm_soal): ?> 
                        <tr>
                           <td width="5">
                              <!--<input type="checkbox" class="flat-red check" name="id[]" value="<?= $bpm_soal->id; ?>">-->
							  <?php 
							  echo $no = $no +1;
							  ?>
                           </td>
                           
                           <td><?php echo($bpm_soal->soal); ?></td>
						   <td><input type="radio" name="angketvalue<?= $bpm_soal->id_soal; ?>" value="1" <?php if ($bpm_soal->hasil==1){echo "checked = 'true'"; } ?>></td>
						   <td><input type="radio" name="angketvalue<?= $bpm_soal->id_soal; ?>" value="2" <?php if ($bpm_soal->hasil==2){echo "checked = 'true'"; } ?>></td>
						   <td><input type="radio" name="angketvalue<?= $bpm_soal->id_soal; ?>" value="3" <?php if ($bpm_soal->hasil==3){echo "checked = 'true'"; } ?>></td>
						   <td><input type="radio" name="angketvalue<?= $bpm_soal->id_soal; ?>" value="4" <?php if ($bpm_soal->hasil==4){echo "checked = 'true'"; } ?>></td>

						   
                           
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($bpm_soal_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Bpm Soal data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>  
				   <button type="submit" class="btn btn-default">Simpan</button>
				
                        <?= form_close(); ?>
				  
				  
				  
               </div>
               <hr>
               
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->

		</div>
	</div>




<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_cdc_member').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/cdc_member/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>
